apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-deployment
  labels:
    app: exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam
  template:
    metadata:
      labels:
        app: exam
    spec:
      containers:
      - name: exam
        image: kobi070/exam:latest 
        ports:
        - containerPort: 5001
        env:
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        imagePullPolicy: Always
