pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKER_REGISTRY = 'kobi070'
        REPO_NAME = 'exam'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'dev', url: 'https://github.com/kobi070/e2e-devops.git'
            }
        }
        
        stage('install Lint & Security Scan') {
            steps {
                sh 'ls -l'
                sh 'pip install flake8 bandit'
            }
        }

        stage('Parallel Lint & Security Scan') {
            steps {
                parallel(
                    Lint: {
                        sh 'flake8 . || true'
                    },
                    Security: {
                        sh 'bandit -r . || true'
                    }
                )
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r docker/requirements.txt'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh "docker build -t $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG exam-code/docker/fe"
                sh "docker tag $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG $DOCKER_REGISTRY/$REPO_NAME:latest"
            }
        }
        
        stage('Run Tests in Container') {
            steps {
                sh "docker run --rm $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG pytest tests/"
            }
        }

        
        
      stage('Integration Test with Docker Compose') {
            steps {
                dir('docker') {
                    sh 'curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
                    sh 'chmod +x /usr/local/bin/docker-compose'
                    sh 'docker-compose --version'
                    sh 'cat docker-compose.yaml'
                    sh 'docker-compose -f docker-compose.yaml up -d'
                    sleep time: 10, unit: 'SECONDS'  // Wait for services to start
                    sh 'docker ps -a  && echo "Port 5001 is mapped and the container is running." ' // Adjust port for backend if needed
                    sh 'docker-compose -f docker-compose.yaml down'
                }
            }
        }

        
        stage('Push to Docker Hub') {
            steps {
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
                sh "docker push $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG"
                sh "docker push $DOCKER_REGISTRY/$REPO_NAME:latest"
            }
        }
        
    }
}